// BIOL 40B — Cranial Nerves trainer (its own page). Same engine as the model
// practical (app.js reads the global MODELS). Inferior view of the brain; the
// diagram's numbered tags are deliberately NOT in Roman-numeral order, so the tag
// never gives the answer away. The Roman numeral is part of the name to learn.
// `roots` = a spelling aid: the word broken into its Greek/Latin parts with meanings.
const MODELS = [
{
  id:"cranial", title:"Cranial Nerves (inferior view)", image:"images/cranial_nerves.jpg", numColor:"#d22",
  items:[
    {n:1,  name:"Olfactory nerve (I)",         accept:["olfactory nerve","olfactory","olfactory nerve i","olfactory i","olfactory nerve 1","cranial nerve i","cranial nerve 1","cn i","cn 1","first cranial nerve"], func:"Smell.", roots:"olfact- (to smell) + -ory", fkeys:["smell","olfaction","odor","odour","scent"]},
    {n:2,  name:"Oculomotor nerve (III)",      accept:["oculomotor nerve","oculomotor","oculomotor nerve iii","oculomotor iii","oculomotor nerve 3","cranial nerve iii","cranial nerve 3","cn iii","cn 3","third cranial nerve"], func:"Moves most eye muscles; constricts the pupil and raises the eyelid.", roots:"oculo- (eye) + motor (mover)", fkeys:["eye","pupil","eyelid","move","constrict","accommod"]},
    {n:3,  name:"Trochlear nerve (IV)",        accept:["trochlear nerve","trochlear","trochlear nerve iv","trochlear iv","trochlear nerve 4","cranial nerve iv","cranial nerve 4","cn iv","cn 4","fourth cranial nerve"], func:"Moves the eye (superior oblique muscle).", roots:"trochlea (pulley — its muscle loops through one)", fkeys:["eye","move","superior oblique","oblique","down"]},
    {n:4,  name:"Abducens nerve (VI)",         accept:["abducens nerve","abducens","abducent nerve","abducens nerve vi","abducens vi","abducens nerve 6","cranial nerve vi","cranial nerve 6","cn vi","cn 6","sixth cranial nerve"], func:"Moves the eye laterally (lateral rectus muscle).", roots:"ab- (away) + ducens (to lead → pulls the eye outward)", fkeys:["eye","lateral","abduct","move","lateral rectus"]},
    {n:5,  name:"Vestibulocochlear nerve (VIII)", accept:["vestibulocochlear nerve","vestibulocochlear","auditory nerve","vestibulocochlear nerve viii","vestibulocochlear viii","vestibulocochlear nerve 8","cranial nerve viii","cranial nerve 8","cn viii","cn 8","eighth cranial nerve"], func:"Hearing and balance (equilibrium).", roots:"vestibulo- (balance chamber) + cochlea (snail shell)", fkeys:["hearing","hear","balance","equilibrium","sound","auditory"]},
    {n:6,  name:"Hypoglossal nerve (XII)",     accept:["hypoglossal nerve","hypoglossal","hypoglossal nerve xii","hypoglossal xii","hypoglossal nerve 12","cranial nerve xii","cranial nerve 12","cn xii","cn 12","twelfth cranial nerve"], func:"Moves the tongue.", roots:"hypo- (under) + gloss- (tongue)", fkeys:["tongue","move"]},
    {n:7,  name:"Accessory nerve (XI)",        accept:["accessory nerve","accessory","spinal accessory nerve","accessory nerve xi","accessory xi","accessory nerve 11","cranial nerve xi","cranial nerve 11","cn xi","cn 11","eleventh cranial nerve"], func:"Moves the neck and shoulders (trapezius and sternocleidomastoid).", roots:"access- (added/helping) — an 'extra' nerve to the neck", fkeys:["neck","shoulder","trapezius","sternocleidomastoid","move","head","shrug"]},
    {n:8,  name:"Optic nerve (II)",            accept:["optic nerve","optic","optic nerve ii","optic ii","optic nerve 2","cranial nerve ii","cranial nerve 2","cn ii","cn 2","second cranial nerve"], func:"Vision (sight).", roots:"opt- (sight/eye) + -ic", fkeys:["vision","sight","see","visual","eyesight"]},
    {n:9,  name:"Trigeminal nerve (V)",        accept:["trigeminal nerve","trigeminal","trigeminal nerve v","trigeminal v","trigeminal nerve 5","cranial nerve v","cranial nerve 5","cn v","cn 5","fifth cranial nerve"], func:"Facial sensation and chewing (mastication).", roots:"tri- (three) + gemini (twins → three branches)", fkeys:["face","facial","sensation","chew","mastication","feel","touch"]},
    {n:10, name:"Facial nerve (VII)",          accept:["facial nerve","facial","facial nerve vii","facial vii","facial nerve 7","cranial nerve vii","cranial nerve 7","cn vii","cn 7","seventh cranial nerve"], func:"Facial expression and taste (anterior tongue).", roots:"faci- (face) + -al", fkeys:["expression","face","facial","taste","smile","tears","saliva"]},
    {n:11, name:"Glossopharyngeal nerve (IX)", accept:["glossopharyngeal nerve","glossopharyngeal","glossopharyngeal nerve ix","glossopharyngeal ix","glossopharyngeal nerve 9","cranial nerve ix","cranial nerve 9","cn ix","cn 9","ninth cranial nerve"], func:"Taste (posterior tongue) and swallowing.", roots:"glosso- (tongue) + pharyng- (throat) + -eal", fkeys:["taste","swallow","tongue","throat","pharynx","saliva"]},
    {n:12, name:"Vagus nerve (X)",             accept:["vagus nerve","vagus","vagus nerve x","vagus x","vagus nerve 10","cranial nerve x","cranial nerve 10","cn x","cn 10","tenth cranial nerve"], func:"Controls the heart, lungs, and digestive organs (parasympathetic).", roots:"vagus (wandering — it roams to many organs)", fkeys:["heart","lung","digest","organ","parasympathetic","viscera","gut","voice","swallow"]},
  ]
},
];
