/* BIOL 40B — Lecture Exam 1 Cram Sheet data.
   High-yield facts distilled from the Lecture Exam 1 + Objective Scope question
   banks, organized by learning-objective topic. Each row: c = cue (stays visible),
   a = answer (hidden until tapped). Some sections carry a mnemonic (mn). */
const LECTURE_CRAM = [
{ id:"organization", title:"1 · NS organization & function", color:"#5A54D6", items:[
  {c:`The 3 sequential functions of the nervous system`, a:`Sensory input → Integration (in the CNS) → Motor output.`},
  {c:`Somatic nervous system — controls & wiring`, a:`Voluntary skeletal muscle; a SINGLE motor neuron runs from CNS straight to the muscle; always uses ACh.`},
  {c:`Autonomic nervous system — controls & wiring`, a:`Involuntary cardiac & smooth muscle + glands; TWO-neuron chain (preganglionic + postganglionic).`},
  {c:`CNS vs PNS`, a:`CNS = brain + spinal cord. PNS = cranial nerves, spinal nerves, and ganglia.`},
]},
{ id:"glia", title:"2 · Neuroglia (support cells)", color:"#5A54D6", items:[
  {c:`Oligodendrocytes`, a:`Myelinate CNS axons (one cell wraps many). Lost → action potentials slow or fail in brain & cord.`},
  {c:`Schwann cells`, a:`Myelinate PNS axons (one cell = one segment); form the regeneration tube that guides PNS regrowth.`},
  {c:`Astrocytes`, a:`Most abundant glia; "end feet" support the blood-brain barrier and regulate the chemical environment.`},
  {c:`Microglia`, a:`The CNS immune cells — phagocytes that clean up debris and pathogens.`},
  {c:`Ependymal cells`, a:`Line the ventricles; cilia circulate CSF; make up the choroid plexus that PRODUCES CSF.`},
]},
{ id:"neuron", title:"3 · Neuron & the action potential", color:"#7C4DD6", items:[
  {c:`Dendrites`, a:`The receiving end — take in incoming chemical signals and generate GRADED potentials.`},
  {c:`Axon (hillock = trigger zone)`, a:`Generates and conducts the action potential toward the axon terminals.`},
  {c:`What maintains the resting membrane potential?`, a:`The Na⁺/K⁺ pump (active transport): 3 Na⁺ OUT, 2 K⁺ IN — keeps the inside negative.`},
  {c:`Depolarization`, a:`Voltage-gated Na⁺ channels open → Na⁺ rushes IN → inside becomes positive.`},
  {c:`Repolarization`, a:`Voltage-gated K⁺ channels open → K⁺ moves OUT → restores the negative resting potential.`},
  {c:`"All-or-none"`, a:`Once threshold is reached, the action potential fires fully — every time the same size.`},
  {c:`Absolute refractory period`, a:`Na⁺ channel INACTIVATION gate is closed; no second AP is possible until the membrane repolarizes.`},
  {c:`Fastest-conducting axon`, a:`Thick + myelinated: large diameter lowers resistance, and myelin allows saltatory ("jumping") conduction.`},
  {c:`Demyelination (e.g., MS)`, a:`Action potentials slow dramatically or fail to reach the terminal.`},
]},
{ id:"synapse", title:"4 · Synapse, graded potentials & summation", color:"#7C4DD6", items:[
  {c:`Graded potential (vs action potential)`, a:`Varies in size with stimulus strength and DEGRADES over short distances (not all-or-none).`},
  {c:`What triggers neurotransmitter release?`, a:`Voltage-gated Ca²⁺ channels open → Ca²⁺ flows into the terminal → vesicles fuse & exocytose.`},
  {c:`EPSP (excitatory)`, a:`Ligand-gated cation channels open → Na⁺ in → DEPOLARIZES → closer to threshold.`},
  {c:`IPSP (inhibitory)`, a:`Cl⁻ in or K⁺ out → HYPERPOLARIZES → farther from threshold.`},
  {c:`Spatial summation`, a:`Multiple inputs from DIFFERENT locations arriving at the SAME time.`},
  {c:`Temporal summation`, a:`The SAME input firing repeatedly in rapid succession (separated in time).`},
  {c:`Ionotropic receptor`, a:`The receptor IS the ion channel — opens immediately → fast, brief response.`},
]},
{ id:"nt", title:"5 · Neurotransmitters & receptors", color:"#7C4DD6", items:[
  {c:`Somatic neuromuscular junction`, a:`Always acetylcholine (ACh) — always excites skeletal muscle.`},
  {c:`All autonomic PREganglionic fibers`, a:`Release ACh onto NICOTINIC receptors of the ganglionic neuron.`},
  {c:`Sympathetic POSTganglionic fibers`, a:`Mostly norepinephrine (NE). Exception: sweat glands use ACh.`},
  {c:`Parasympathetic POSTganglionic fibers`, a:`Acetylcholine onto MUSCARINIC receptors.`},
  {c:`Inhibitory neurotransmitters`, a:`e.g., GABA & glycine — open Cl⁻/K⁺ channels to hyperpolarize.`},
]},
{ id:"cerebrum", title:"6 · Cerebrum & cortex", color:"#2563C9", items:[
  {c:`Precentral gyrus (frontal lobe)`, a:`PRIMARY MOTOR cortex — issues voluntary movement commands (upper motor / Betz cells).`},
  {c:`Postcentral gyrus (parietal lobe)`, a:`PRIMARY SOMATOSENSORY cortex — touch, pressure, proprioception.`},
  {c:`Occipital lobe`, a:`Vision (primary visual cortex). Blow to back of head → visual disturbances.`},
  {c:`Temporal lobe`, a:`Hearing + Wernicke's area (language comprehension).`},
  {c:`Broca's area`, a:`Speech PRODUCTION (frontal). Damage → can't produce fluent speech.`},
  {c:`Wernicke's area`, a:`Language COMPREHENSION. Damage → fluent but nonsensical speech, can't understand.`},
  {c:`Prefrontal cortex`, a:`Executive function, planning, personality (the Phineas Gage case).`},
  {c:`Sensory homunculus (big hands/lips)`, a:`Reflects high receptor DENSITY needing fine sensory discrimination.`},
  {c:`Left hemisphere (most people)`, a:`Language, math, logic/reasoning.`},
  {c:`Corpus callosum`, a:`Massive white-matter tract connecting the two hemispheres. Cut → hemispheres can't share info.`},
  {c:`Basal nuclei`, a:`Plan/regulate/inhibit movement; the DIRECT pathway disinhibits the thalamus → facilitates movement. Parkinson's = substantia nigra dopamine loss.`},
]},
{ id:"deep", title:"7 · Diencephalon, brainstem & cerebellum", color:"#2563C9", items:[
  {c:`Thalamus`, a:`Relay station for almost ALL ascending sensory info headed to the cortex.`},
  {c:`Hypothalamus`, a:`Master homeostasis: temperature, thirst, sleep + top autonomic & endocrine control center.`},
  {c:`Medulla oblongata`, a:`Vital cardiovascular & respiratory centers (trauma = often fatal); site of pyramidal decussation.`},
  {c:`Superior colliculus (midbrain)`, a:`Visual/orienting reflexes — turns head & eyes toward a stimulus.`},
  {c:`Cerebellum`, a:`Compares motor commands vs proprioceptive feedback → smooth, coordinated, balanced movement (alcohol-sensitive).`},
  {c:`Pyramidal (corticospinal) decussation`, a:`Motor fibers cross at the medulla's pyramids → right brain controls the left body.`},
]},
{ id:"protect", title:"8 · Meninges, CSF & blood-brain barrier", color:"#0E8A8A", items:[
  {c:`Meninges, superficial → deep`, a:`DURA → ARACHNOID → PIA mater. (Falx cerebri = dura fold in the longitudinal fissure.)`},
  {c:`CSF is produced by…`, a:`The choroid plexuses (ependymal cells) inside the ventricles.`},
  {c:`CSF is reabsorbed by…`, a:`Arachnoid granulations → into venous blood. Blockage → CSF backs up → ↑ intracranial pressure.`},
  {c:`CSF flow path`, a:`Lateral ventricles → interventricular foramen → 3rd → cerebral aqueduct → 4th → apertures → subarachnoid space.`},
  {c:`Blood-brain barrier`, a:`TIGHT JUNCTIONS between capillary endothelial cells, supported by astrocyte end feet.`},
]},
{ id:"cord", title:"9 · Spinal cord, reflexes & PNS", color:"#0E8A8A", items:[
  {c:`Reflex arc — correct order`, a:`Receptor → Sensory neuron → Integration center → Motor neuron → Effector.`},
  {c:`Sensory (afferent) neuron's job`, a:`Carry the impulse from the receptor TOWARD the CNS.`},
  {c:`Spinal cord ends at ~L1–L2`, a:`Below it is the cauda equina → lumbar puncture is done below L2 to avoid the cord.`},
  {c:`Dorsal column tracts (gracilis & cuneatus)`, a:`Ascending — carry FINE TOUCH + PROPRIOCEPTION.`},
  {c:`Dermatome`, a:`Strip of skin supplied by a single spinal nerve.`},
  {c:`Brachial plexus (C5–T1)`, a:`Shoulder & arm.`},
  {c:`Cervical plexus — phrenic nerve (C3–C5)`, a:`Innervates the diaphragm → breathing.`},
  {c:`Nerve connective-tissue wrappings`, a:`Endoneurium (each axon) → Perineurium (a fascicle) → Epineurium (whole nerve).`},
  {c:`PNS regeneration`, a:`Wallerian degeneration (macrophages clear debris) + Schwann cells form a regeneration tube.`},
]},
{ id:"cn", title:"10 · Cranial nerves I–XII", color:"#D22", mn:[
  {t:`Names, I → XII`, x:`"<b>O</b>h <b>O</b>h <b>O</b>h <b>T</b>o <b>T</b>ouch <b>A</b>nd <b>F</b>eel <b>V</b>ery <b>G</b>ood <b>V</b>elvet, <b>A</b>h <b>H</b>eaven."`},
  {t:`Sensory / Motor / Both`, x:`"<b>S</b>ome <b>S</b>ay <b>M</b>arry <b>M</b>oney <b>B</b>ut <b>M</b>y <b>B</b>rother <b>S</b>ays <b>B</b>ig <b>B</b>rains <b>M</b>atter <b>M</b>ost." (I→XII)`},
], items:[
  {c:`I — Olfactory`, a:`Sensory · smell. (Unique: bypasses the thalamus, straight to cortex & limbic system.)`},
  {c:`II — Optic`, a:`Sensory · vision.`},
  {c:`III — Oculomotor`, a:`Motor · most eye movement + PARASYMPATHETIC pupil constriction & lens accommodation.`},
  {c:`IV — Trochlear`, a:`Motor · superior oblique eye muscle.`},
  {c:`V — Trigeminal`, a:`Both · face & teeth sensation (a dental block hits this), chewing.`},
  {c:`VI — Abducens`, a:`Motor · lateral rectus → abducts the eye. Damage = can't look laterally.`},
  {c:`VII — Facial`, a:`Both · facial expression, taste (anterior ⅔), tears & salivation.`},
  {c:`VIII — Vestibulocochlear`, a:`Sensory · hearing & balance.`},
  {c:`IX — Glossopharyngeal`, a:`Both · taste (posterior ⅓), swallowing, salivation.`},
  {c:`X — Vagus`, a:`Both · ~90% of parasympathetic outflow to thoracic & abdominal organs (slows heart, etc.).`},
  {c:`XI — Accessory`, a:`Motor · trapezius & sternocleidomastoid.`},
  {c:`XII — Hypoglossal`, a:`Motor · tongue movement.`},
  {c:`Taste lost, texture intact →`, a:`CN VII, IX (and X) — the gustatory nerves.`},
]},
{ id:"ans", title:"11 · Autonomic nervous system", color:"#C9720E", items:[
  {c:`Sympathetic — origin & nickname`, a:`THORACOLUMBAR (T1–L2); short pre-, long postganglionic fibers; "fight or flight."`},
  {c:`Parasympathetic — origin & nickname`, a:`CRANIOSACRAL; long pre-, short postganglionic fibers; "rest & digest."`},
  {c:`Sympathetic effects`, a:`↑ heart rate, dilate pupils & bronchioles, shunt blood to skeletal muscle, mobilize glucose.`},
  {c:`Parasympathetic effects`, a:`↓ heart rate, constrict pupils & bronchioles, ↑ digestion & glandular activity.`},
  {c:`Resting heart-rate tone`, a:`Parasympathetic (vagus) dominates — slows the SA node's intrinsic ~100 bpm down to ~70.`},
  {c:`Adrenal medulla`, a:`A modified sympathetic ganglion — chromaffin cells dump EPINEPHRINE + norepinephrine into the blood.`},
  {c:`Controlled EXCLUSIVELY by sympathetic (no dual)`, a:`Most blood vessels, sweat glands, and arrector pili muscles.`},
  {c:`Pupillary light reflex (bright light)`, a:`Parasympathetic (CN III) → circular iris muscle contracts → pupil CONSTRICTS.`},
  {c:`Atropine (muscarinic blocker)`, a:`Blocks parasympathetic → sympathetic dominates → ↑ heart rate, dilated pupils.`},
  {c:`Autonomic terminals = varicosities`, a:`Bead-like swellings that release NT over a wide area (vs one synaptic end bulb at the NMJ).`},
  {c:`White rami communicantes`, a:`Myelinated PREganglionic sympathetic fibers entering the chain ganglion.`},
]},
{ id:"receptors", title:"12 · Sensory receptors", color:"#1F8A4C", items:[
  {c:`Nociceptors`, a:`PAIN — tissue-damaging stimuli (extreme temp, pressure, chemicals).`},
  {c:`Mechanoreceptors`, a:`Touch, pressure, stretch, vibration.`},
  {c:`Proprioceptors`, a:`Body position & movement — in muscles, tendons, and joints.`},
  {c:`Photoreceptors`, a:`Light — rods & cones of the retina.`},
  {c:`Chemoreceptors`, a:`Chemicals — taste, smell, and blood chemistry.`},
]},
{ id:"eye", title:"13 · The eye & vision", color:"#1F8A4C", mn:[
  {t:`Light's path`, x:`<b>Cornea → aqueous humor → pupil → lens → vitreous humor → retina.</b> Trace it and the parts fall in order.`},
], items:[
  {c:`Accommodation (focusing near)`, a:`Parasympathetic → ciliary muscle CONTRACTS → suspensory ligaments loosen → lens bulges rounder.`},
  {c:`Rods`, a:`Dim-light & peripheral vision; very sensitive; NO color.`},
  {c:`Cones`, a:`Color + high-acuity vision; densest at the fovea centralis.`},
  {c:`Fovea centralis`, a:`Center of the macula — ONLY cones, no overlying vessels → sharpest vision.`},
  {c:`Optic disc`, a:`The blind spot — where the optic nerve exits; no photoreceptors.`},
  {c:`Pigmented retinal layer`, a:`Absorbs stray light so it doesn't scatter (keeps images sharp).`},
  {c:`Optic chiasm compressed (center)`, a:`Crossing medial-retina fibers lost → lose LATERAL (peripheral) fields in both eyes (bitemporal hemianopia).`},
  {c:`Glaucoma`, a:`Aqueous humor can't drain via the scleral venous sinus → ↑ intraocular pressure → compresses retina/optic nerve.`},
  {c:`Cataracts`, a:`Clouding of the normally transparent lens.`},
  {c:`Retinal detachment`, a:`Neural & pigmented layers separate; classic "curtain drawn across the eye."`},
]},
{ id:"ear", title:"14 · The ear: hearing & balance", color:"#1F8A4C", mn:[
  {t:`The 3 ossicles, in order`, x:`<b>Malleus → Incus → Stapes</b> = Hammer → Anvil → Stirrup.`},
], items:[
  {c:`Sound path to the inner ear`, a:`Tympanic membrane → malleus → incus → stapes → OVAL WINDOW → fluid of the cochlea.`},
  {c:`Ossicles' job`, a:`Mechanically amplify & transmit vibration from the eardrum to the oval window.`},
  {c:`Hearing transduction`, a:`Fluid waves bend the stereocilia of hair cells (organ of Corti) → ion channels open → action potential.`},
  {c:`Semicircular canals (ampulla + cupula)`, a:`DYNAMIC (rotational) equilibrium — head turns; fluid lags and bends the cupula.`},
  {c:`Utricle & saccule (maculae + otoliths)`, a:`STATIC equilibrium + linear acceleration (tilt/straight-line motion).`},
  {c:`Conductive hearing loss`, a:`Mechanical block of sound transmission — e.g., otosclerosis (stapes fixed).`},
  {c:`Sensorineural hearing loss`, a:`Damage to hair cells (organ of Corti) or the vestibulocochlear nerve (CN VIII).`},
]},
];
